name: collapsible_navigation_bar
description: A customizable collapsible navigation bar
version: 1.0.0
homepage: https://github.com/melikhanHosdogdu
repository: https://github.com/melikhanHosdogdu/collapsible_navigation_bar/
documentation: https://github.com/melikhanHosdogdu/collapsible_navigation_bar/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
